version: '3.8'

services:
  redis:
    image: redis:alpine            
    container_name: redis_db
    ports:
      - "6379:6379"              
    networks:
      - app_network

  kafka_examples:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka_examples
    ports:
      - "29092:29092" # Porta per accesso esterno (dal tuo PC)
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      # CONFIGURAZIONE CRUCIALE:
      # - PLAINTEXT://kafka_examples:9092 -> Usato dai container (UserMicroservice, DataCollector)
      # - PLAINTEXT_HOST://localhost:29092 -> Usato dal tuo PC (se ti serve debuggare)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_examples:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka_examples:29093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      # Questi prevengono errori se hai un solo nodo
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - app_network
    # Aggiungi un check per sapere quando Ã¨ pronto
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka_examples:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5

  
  usermanager:
    build: ./UserManagerMicroservice
    container_name: usermanager
    environment:
      - DB_HOST=mysql-db
      - FLASK_RUN_HOST=0.0.0.0
      - TARGET_GRPC_HOST=datacollector:50052
      - REDIS_HOST=redis
    ports:
      - "5000:5000"  
      - "50051:50051" 
    networks:
      - app_network   
      - existing_db_net 

  datacollector:
    build: ./DataCollectorMicroservice
    container_name: datacollector
    depends_on:
      usermanager:
        condition: service_started
      kafka_examples:
        condition: service_healthy
    environment:
      - DB_HOST=mysql-db
      - FLASK_RUN_HOST=0.0.0.0
      - TARGET_GRPC_HOST=usermanager:50051
    ports:
      - "5005:5005"
      - "50052:50052"
    networks:
      - app_network
      - existing_db_net

networks:
  app_network:
    driver: bridge
  

  existing_db_net:
    external: true
    name: composedatabase_default

volumes:
  kafka-data:
