apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Credenziali DB (dal tuo DbManager.py)
  DB_USER: "anto"
  DB_PASSWORD: "onta"
  # OpenSky API (dal tuo credentials.json)
  CLIENT_ID: "davidepanto@gmail.com-api-client"
  CLIENT_SECRET: "ewpHTQ27KoTGv4vMoCyLT8QrIt4sLr3z"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 80;
            location /user/ {
                rewrite ^/user/(.*) /$1 break;
                # Nota: usermanager-service è il nome del servizio K8s
                proxy_pass http://usermanager-service:5000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
            location /data/ {
                rewrite ^/data/(.*) /$1 break;
                # Nota: datacollector-service è il nome del servizio K8s
                proxy_pass http://datacollector-service:5005;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }